# CCTS whole project container configuration
version: "3"
services:
  postgres:
    image: postgres
    healthcheck:
      test: psql postgres --command "select 1" -U postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

  pact_broker:
    image: pactfoundation/pact-broker
    ports:
      - "10141:9292"
    depends_on:
      - postgres
    environment:
      PACT_BROKER_DATABASE_URL_ENVIRONMENT_VARIABLE_NAME: DATABASE_URL
      DATABASE_URL: "postgres://postgres:password@postgres/postgres"
      PACT_BROKER_DATABASE_USERNAME: postgres
      PACT_BROKER_DATABASE_PASSWORD: password
      PACT_BROKER_DATABASE_HOST: postgres
      PACT_BROKER_DATABASE_NAME: postgres
      PACT_BROKER_PORT: "9292"
      PACT_BROKER_LOG_LEVEL: INFO

  rabbitmq:
    image: docker.io/bitnami/rabbitmq:3.8
    ports:
      # rabbitMQ server port
      - '10109:5672'
      # rabbitMq server management port
      - '10110:15672'
      # idk what belows use for
      - '4369:4369'
      - '25672:25672'
    environment:
      - RABBITMQ_SECURE_PASSWORD=yes
      - RABBITMQ_USERNAME=soselab
      - RABBITMQ_PASSWORD=soselab401
      # safer disk space
      - RABBITMQ_DISK_FREE_RELATIVE_LIMIT=1.0
    volumes:
      # - 'rabbitmq_data:/bitnami'
      - rabbitmq-volume:/bitnami

#  if use docker volume
# volumes:
#   rabbitmq_data:
#     driver: local
  ccts:
    image: ccts
    ports:
#    for api endpoint
    - '58080:58080'

  local-mongodb:
    image: mongo:latest
    container_name: local-mongodb
    environment:
      MONGO_INITDB_DATABASE: CCTS # 這個記得換掉
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./mongo-volume:/data/db:Z
    ports:
      - 27017:27017


volumes:
  postgres-volume:
  rabbitmq-volume: