server:
  port: 58093
spring:
  data:
    mongodb:
      uri:
  rabbitmq:
    username: 'soselab'
    password: 'soselab401'
    host: 140.121.196.23
    port: 10109
    virtual-host: /
    listener:
      simple:
        # 手動ack, 確保訊息完整處理
        acknowledge-mode: manual

CCTS:
  pact_broker: http://23.dfder.tw:10141