server:
  port: 58080
spring:
  data:
    mongodb:
      uri: mongodb://soselab:soselab401@local-mongodb:27017/CCTS?authSource=CCTS
  rabbitmq:
    username: 'soselab'
    password: 'soselab401'
    host: rabbitmq
    port: 5672
    virtual-host: /
    listener:
      simple:
        # 手動ack, 確保訊息完整處理
        acknowledge-mode: manual

CCTS:
  pact_broker: http://pact_broker:9092