server:
  port: 58093
spring:
  data:
    mongodb:
      uri: mongodb+srv://df:dfder@clusters.owt5s.mongodb.net/CCTS?retryWrites=true&w=majority
  rabbitmq:
    username: 'soselab'
    password: 'soselab401'
    host: ccts
    port: 5672
    virtual-host: /
    listener:
      simple:
        # 手動ack, 確保訊息完整處理
        acknowledge-mode: manual

CCTS:
  pact_broker: http://pact_broker:9092